CREST-7: cleaning up examples
illumio/terraform-provider-illumio-core pull request #21
Opened 2021-09-27 23:46 UTC by kyongkim-illumio

Cleaning up some examples. User reported incorrect source and version. Also found an issue with ip_list example.

2021-09-29 22:02 UTC, dsommerville-illumio requested changes
LGTM, just one small nit.

We should clean up these examples as this amount seems a bit unmanageable. What are the most important endpoints?

2021-09-29 22:02 UTC, dsommerville-illumio commented on examples/ip_list/main.tf
> +    // to_ip = "1.1.0.254"
Why are these commented out? Are we not sure what the values should be here?

2021-09-29 22:08 UTC, kyongkim-illumio commented on examples/ip_list/main.tf
> +    // to_ip = "1.1.0.254"
I wanted to show both examples of CIDR for from_ip and individual ip for from_ip and to_ip. I can remove it if it makes it look sloppy.

2021-09-29 22:12 UTC, dsommerville-illumio commented on examples/ip_list/main.tf
> +    // to_ip = "1.1.0.254"
That makes sense - can you add a comment to explain that above?

2021-09-30 22:50 UTC, dsommerville-illumio approved these changes
Looks good, thanks!

2021-09-30 22:54 UTC, merged